language: php

php:
  - 7.1
  - 7.2

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "us-west-2"  
  app: "myphp"
  env: "Myphp-env"
  bucket_name: "$S3BUCKET"
  on:
    branch: master

notifications:
  email: false
